services:
  - type: web
    name: jiosaavn-api-prod
    env: python
    region: singapore  # Best for Asian traffic
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: ENVIRONMENT
        value: production
    autoDeploy: true
    healthCheckPath: /
    plan: free
    branch: main # or master, depending on your default branch name

  - type: web
    name: jiosaavn-api-dev
    env: python
    region: singapore  # Best for Asian traffic
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: ENVIRONMENT
        value: development
      - key: DEBUG
        value: "true"
    autoDeploy: true
    healthCheckPath: /
    plan: free
    branch: develop 